package com.model;



/**
 * State generated by MyEclipse - Hibernate Tools
 */

public class State  implements java.io.Serializable {


    // Fields    

     private Integer stateId;
     private Country country;
     private String stateName;


    // Constructors

    /** default constructor */
    public State() {
    }

    
    /** full constructor */
    public State(Integer stateId, Country country, String stateName) {
        this.stateId = stateId;
        this.country = country;
        this.stateName = stateName;
    }

   
    // Property accessors

    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
   








}