package com.model;

// Generated Nov 5, 2015 9:48:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * Batch generated by hbm2java
 */
public class Batch implements java.io.Serializable {

	private Integer batchId;
	private String batchName;
	private int facultyId;

	public Batch() {
	}

	public Batch(String batchName, int facultyId) {
		this.batchName = batchName;
		this.facultyId = facultyId;
	}

	public Integer getBatchId() {
		return this.batchId;
	}

	public void setBatchId(Integer batchId) {
		this.batchId = batchId;
	}

	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public int getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

}
