package com.model;

// Generated Nov 5, 2015 9:48:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * Faculty generated by hbm2java
 */
public class Faculty implements java.io.Serializable {

	private Integer facultyId;
	private String facultyName;
	private int courseId;
	private String funame;
	private String fpass;

	public Faculty() {
	}

	public Faculty(String facultyName, int courseId, String funame, String fpass) {
		this.facultyName = facultyName;
		this.courseId = courseId;
		this.funame = funame;
		this.fpass = fpass;
	}

	public Integer getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(Integer facultyId) {
		this.facultyId = facultyId;
	}

	public String getFacultyName() {
		return this.facultyName;
	}

	public void setFacultyName(String facultyName) {
		this.facultyName = facultyName;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getFuname() {
		return this.funame;
	}

	public void setFuname(String funame) {
		this.funame = funame;
	}

	public String getFpass() {
		return this.fpass;
	}

	public void setFpass(String fpass) {
		this.fpass = fpass;
	}

}
