package com.model;

// Generated Nov 5, 2015 9:48:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * Stud generated by hbm2java
 */
public class Stud implements java.io.Serializable {

	private Integer id;
	private String uname;
	private String pass;

	public Stud() {
	}

	public Stud(String uname, String pass) {
		this.uname = uname;
		this.pass = pass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
