package com.model;

// Generated Nov 5, 2015 9:48:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer rollno;
	private String studName;
	private int batchId;
	private String uname;
	private String pass;
	private String lname;

	public Student() {
	}

	public Student(String studName, int batchId, String uname, String pass,
			String lname) {
		this.studName = studName;
		this.batchId = batchId;
		this.uname = uname;
		this.pass = pass;
		this.lname = lname;
	}

	public Integer getRollno() {
		return this.rollno;
	}

	public void setRollno(Integer rollno) {
		this.rollno = rollno;
	}

	public String getStudName() {
		return this.studName;
	}

	public void setStudName(String studName) {
		this.studName = studName;
	}

	public int getBatchId() {
		return this.batchId;
	}

	public void setBatchId(int batchId) {
		this.batchId = batchId;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

}
